load("@io_bazel_rules_scala//scala:scala.bzl", "scala_specs2_junit_test")

scala_specs2_junit_test(
    name = "scala_example2_test",
    size = "small",
    srcs = ["Example2Test.scala"],
    deps = ["//m0/src/main/scala/com/example2:scala_example2"],
    suffixes = ["Test"],
)