package(default_visibility = ["//visibility:public"])
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")

scala_library(
    name="scala_example",
    srcs=[
        "Example.scala",
        ]
)

scala_library(
    name="scala_example3",
    srcs=[
        "Example3.scala",
        ]
)