http_archive(
             name = "io_bazel_rules_scala",
             url = "https://github.com/bazelbuild/rules_scala/archive/dffcc54c3f35b8615f84a96fbf4e93f9203e80ab.zip",
             type = "zip",
             strip_prefix= "rules_scala-dffcc54c3f35b8615f84a96fbf4e93f9203e80ab"
             )

# git_repository(
#    name = "io_bazel_rules_scala",
#    remote = "https://github.com/bazelbuild/rules_scala.git",
#    commit = "73743b830ae98d13a946b25ad60cad5fee58e6d3", # update this as needed
# )

load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")
scala_repositories()

load("@io_bazel_rules_scala//specs2:specs2_junit.bzl","specs2_junit_repositories")
specs2_junit_repositories()



maven_jar(
    name = "com_fasterxml_jackson_datatype_jackson_datatype_joda",
    artifact = "com.fasterxml.jackson.datatype:jackson-datatype-joda:2.6.7",
)

maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:19.0",
)