http_archive(
             name = "io_bazel_rules_scala",
             url = "https://github.com/bazelbuild/rules_scala/archive/d916599d38de29085e5ca9eae167716c4f150a02.zip",
             type = "zip",
             strip_prefix= "rules_scala-d916599d38de29085e5ca9eae167716c4f150a02"
             )

# git_repository(
#    name = "io_bazel_rules_scala",
#    remote = "https://github.com/bazelbuild/rules_scala.git",
#    commit = "73743b830ae98d13a946b25ad60cad5fee58e6d3", # update this as needed
# )

load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")
scala_repositories()

load("@io_bazel_rules_scala//specs2:specs2_junit.bzl","specs2_junit_repositories")
specs2_junit_repositories()